version: "3"

services:
    cms:
#        image: christiangroeber/php-server:8.1.2
        build:
            context: .
            dockerfile: Dockerfile
        container_name: cms
        ports:
            - '94:80'
        volumes:
            - /home/christian/PhpstormProjects/journal/content:/var/www/html/content
            - /home/christian/PhpstormProjects/journal/media:/var/www/html/media
            - /home/christian/PhpstormProjects/journal/data:/var/www/html/data
            - ./:/var/www/html
        environment:
            CMS_DIR: 'pixl-cms/'
            SECRET: 'asdf'
            INI_ZEND_EXTENSION: 'xdebug.so'
            XDEBUG_MODE: 'debug'
            XDEBUG_CLIENT_HOST: '127.0.0.1'
            XDEBUG_START_WITH_REQUEST: 'yes'
            XDEBUG_DISCOVER_CLIENT_HOST: 'true'
            XDEBUG_CLIENT_PORT: '33333'
